#include "merge_sort.h"
#include "insertion_sort.h"
#include "selection_sort.h"
#include "binary_search.h"
#include "maximum_subarray.h"
#include "heapsort.h"
#include "quicksort.h"
#include "counting_sort.h"
#include "radix_sort.h"
#include "bucket_sort.h"
#include "linked_list.h"
#include "basic_tree.h"
#include "hash_table.h"
#include "hash_table_open.h" //buggy, doesnt work
#include "binary_search_tree.h"
#include "red_black_tree.h"
#include "order_statistic_tree.h"
#include "binary_search_tree_aug.h" //augmented to have O(1) Successor, Min, Max, Predecessor, deletion NOT COMPLETED
#include "interval_tree.h"